### PR TITLE
[EasyHttpClient] Fix default http client id for Symfony 6.3

### PR DESCRIPTION
**Pull request by alexndlm**
| Q             | A
| ------------- | ---
| Bug fix?      | yes
| New feature?  | no
| BC breaks?    | no
| Deprecations? | no
| Tests pass?   | yes

https://github.com/symfony/symfony/pull/49513

And make it test-friendly.

### CODE REVIEW

**Review by akl-95 — APPROVED** [review]
Code review successful. 🎉 Awesome work!

- [X] Functionality and requirements
- [X] Code organization and structure
- [X] Code readability and maintainability
- [X] Error handling and exception management
- [X] Security considerations (POL-015)

**Review by akl-95 — DISMISSED** [review]
🏅🎖️👏

- [X] Functionality and requirements
- [X] Code organization and structure
- [X] Code readability and maintainability
- [X] Error handling and exception management
- [X] Security considerations (POL-015)

**Review by itorgov — APPROVED** [review]
Approved! ✔️ Code review complete.

- [X] Functionality and requirements
- [X] Code organization and structure
- [X] Code readability and maintainability
- [X] Error handling and exception management
- [X] Security considerations (POL-015)

**Review by roman-eonx — APPROVED** [review]
Thanks @alexndlm. 🎉🚀👍

- [X] Functionality and requirements
- [X] Code organization and structure
- [X] Code readability and maintainability
- [X] Error handling and exception management
- [X] Security considerations (POL-015)

**Review by akl-95 — APPROVED** [review]
🎊👨‍💻👩‍💻

- [X] Functionality and requirements
- [X] Code organization and structure
- [X] Code readability and maintainability
- [X] Error handling and exception management
- [X] Security considerations (POL-015)

**Pull request merged**
