### PR TITLE
[EasyErrorHandler] Validation exception instead of 500 when input data is misformatted

### PR DESCRIPTION
**Pull request by skrut**
- improved easy error handler

| Q             | A
| ------------- | ---
| Bug fix?      | no
| New feature?  | yes 
| BC breaks?    | no   
| Deprecations? | no 
| Tests pass?   | yes    
| Fixed tickets | #

### CODE REVIEW

**Review by itorgov — APPROVED** [review]
🚀👏👌

- [X] Functionality and requirements
- [X] Code organization and structure
- [X] Code readability and maintainability
- [X] Error handling and exception management
- [X] Security considerations (POL-015)

**Review by roman-eonx — APPROVED** [review]
Congratulations! Code review passed.

- [X] Functionality and requirements
- [X] Code organization and structure
- [X] Code readability and maintainability
- [X] Error handling and exception management
- [X] Security considerations (POL-015)

**Review by itorgov — APPROVED** [review]
approved

- [X] Functionality and requirements
- [X] Code organization and structure
- [X] Code readability and maintainability
- [X] Error handling and exception management
- [X] Security considerations (POL-015)

**Review by roman-eonx — APPROVED** [review]
Good job! 👍 Code review approved.

- [X] Functionality and requirements
- [X] Code organization and structure
- [X] Code readability and maintainability
- [X] Error handling and exception management
- [X] Security considerations (POL-015)

**Pull request merged**
