### PR TITLE
[EasyTest] UniqueGroupProvider for Faker

### PR DESCRIPTION
**Pull request by zeromodule**
| Q             | A
| ------------- | ---
| Bug fix?      | no
| New feature?  | yes 
| BC breaks?    | no     
| Deprecations? | no 
| Tests pass?   | yes    

With the unique generator you are guaranteed to never get the same combination of values within the same group.
`$faker->uniqueGroup('group-name')->randomElement([1, 2, 3]);`

The provider was originally implemented for PG, but now it's needed in other projects (e.g. AVC).

### CODE REVIEW

**Review by alexndlm — DISMISSED** [review]
No changes required

- [X] Functionality and requirements
- [X] Code organization and structure
- [X] Code readability and maintainability
- [X] Error handling and exception management
- [X] Security considerations (POL-015)

**Review by akl-95 — APPROVED** [review]
👌🌟👏

- [X] Functionality and requirements
- [X] Code organization and structure
- [X] Code readability and maintainability
- [X] Error handling and exception management
- [X] Security considerations (POL-015)

**Review by alexndlm — APPROVED** [review]
Nice work! Code review complete.

- [X] Functionality and requirements
- [X] Code organization and structure
- [X] Code readability and maintainability
- [X] Error handling and exception management
- [X] Security considerations (POL-015)

**Review by itorgov — APPROVED** [review]
Code review successful. 👏 Nice work!

- [X] Functionality and requirements
- [X] Code organization and structure
- [X] Code readability and maintainability
- [X] Error handling and exception management
- [X] Security considerations (POL-015)

**Review by roman-eonx — APPROVED** [review]
Code review passed. 👌 Excellent work!

- [X] Functionality and requirements
- [X] Code organization and structure
- [X] Code readability and maintainability
- [X] Error handling and exception management
- [X] Security considerations (POL-015)

**Review by akl-95 — APPROVED** [review]
Code review complete. 🚀 Excellent job!

- [X] Functionality and requirements
- [X] Code organization and structure
- [X] Code readability and maintainability
- [X] Error handling and exception management
- [X] Security considerations (POL-015)

**Pull request merged**
