### PR TITLE
[EasyUtils] update number to money string convert logic

### PR DESCRIPTION
**Pull request by skrut**
- updated number to money converting

| Q             | A
| ------------- | ---
| Bug fix?      | no
| New feature?  | yes 
| BC breaks?    | no     
| Deprecations? | yes/no 
| Tests pass?   | yes    
| Fixed tickets | #...

### CODE REVIEW

**Review by itorgov — DISMISSED** [review]
Thanks @skrut. Code review passed. Well done!

- [X] Functionality and requirements
- [X] Code organization and structure
- [X] Code readability and maintainability
- [X] Error handling and exception management
- [X] Security considerations (POL-015)

**Review by itorgov — APPROVED** [review]
Code review approved. 😊 Nice work!

- [X] Functionality and requirements
- [X] Code organization and structure
- [X] Code readability and maintainability
- [X] Error handling and exception management
- [X] Security considerations (POL-015)

**Review by alexndlm — APPROVED** [review]
Thanks @skrut. Excellent work! Code review complete.

- [X] Functionality and requirements
- [X] Code organization and structure
- [X] Code readability and maintainability
- [X] Error handling and exception management
- [X] Security considerations (POL-015)

**Review by egor-dev — APPROVED** [review]
Awesome job! Code review passed.

- [X] Functionality and requirements
- [X] Code organization and structure
- [X] Code readability and maintainability
- [X] Error handling and exception management
- [X] Security considerations (POL-015)

**Pull request merged**
