### PR TITLE
[EasyApiPlatform] Allow filter by IRI for entityId field

### PR DESCRIPTION
**Pull request by alexndlm**
| Q             | A
| ------------- | ---
| Bug fix?      | no
| New feature?  | yes
| BC breaks?    | no
| Deprecations? | no
| Tests pass?   | yes

### CODE REVIEW

**Review by itorgov — APPROVED** [review]
Code review passed. Congratulations!

- [X] Functionality and requirements
- [X] Code organization and structure
- [X] Code readability and maintainability
- [X] Error handling and exception management
- [X] Security considerations (POL-015)

**Review by akl-95 — APPROVED** [review]
Code review complete. 🎊 Well done!

- [X] Functionality and requirements
- [X] Code organization and structure
- [X] Code readability and maintainability
- [X] Error handling and exception management
- [X] Security considerations (POL-015)

**Review by roman-eonx — APPROVED** [review]
Code review passed. Congratulations!

- [X] Functionality and requirements
- [X] Code organization and structure
- [X] Code readability and maintainability
- [X] Error handling and exception management
- [X] Security considerations (POL-015)

**Review by roman-eonx — DISMISSED** [review]
Thanks @alexndlm. Code review approved. Keep up the good work!

- [X] Functionality and requirements
- [X] Code organization and structure
- [X] Code readability and maintainability
- [X] Error handling and exception management
- [X] Security considerations (POL-015)

**Review by akl-95 — DISMISSED** [review]
Code review approved. 👏 Keep up the good work!

- [X] Functionality and requirements
- [X] Code organization and structure
- [X] Code readability and maintainability
- [X] Error handling and exception management
- [X] Security considerations (POL-015)

**Review by itorgov — DISMISSED** [review]
Thanks @alexndlm. Code review successful. 👏 Nice work!

- [X] Functionality and requirements
- [X] Code organization and structure
- [X] Code readability and maintainability
- [X] Error handling and exception management
- [X] Security considerations (POL-015)

**Review by itorgov — APPROVED** [review]
👏💯🎉

- [X] Functionality and requirements
- [X] Code organization and structure
- [X] Code readability and maintainability
- [X] Error handling and exception management
- [X] Security considerations (POL-015)

**Review by akl-95 — APPROVED** [review]
Code review passed. 🚀 Great work!

- [X] Functionality and requirements
- [X] Code organization and structure
- [X] Code readability and maintainability
- [X] Error handling and exception management
- [X] Security considerations (POL-015)

**Pull request merged**
